# Generated by Django 5.0.4 on 2024-04-10 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Группа курса',
                'verbose_name_plural': 'Группы курсов',
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('users', models.ManyToManyField(db_table='UserCourse', related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
                ('groups', models.ManyToManyField(db_table='CourseGroup', related_name='courses', to='courses.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'Course',
            },
        ),
    ]
