# Generated by Django 5.0.4 on 2024-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='apps/', verbose_name='Изображение')),
                ('href', models.URLField(verbose_name='Ссылка для скачивания')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'db_table': 'App',
            },
        ),
        migrations.CreateModel(
            name='HandBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='hand-books-image/', verbose_name='Изображение')),
                ('file', models.FileField(upload_to='hand-books-files/', verbose_name='Файл (необязательно)')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'db_table': 'HandBook',
            },
        ),
    ]
